# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-06 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_auto_20151231_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasificacion',
            options={'ordering': ['descripcion'], 'verbose_name_plural': 'Clasificaciones'},
        ),
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'ordering': ['descripcion'], 'verbose_name_plural': 'Ubicaciones'},
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='fecha_Mvto',
            field=models.DateField(verbose_name=b'Fecha Movimiento'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='tipomvto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.TipoMvto', verbose_name=b'Tipo de Movimiento'),
        ),
    ]
