# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-07 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0024_auto_20160106_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventario.EstadoArticulo'),
        ),
    ]
