# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-05 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0005_requerimiento_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiporequerimiento',
            name='otro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soporte.TipoRequerimiento'),
        ),
    ]
